name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.40'
          - '5.36'
          - '5.34'
          - '5.32'
          - '5.10'
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    name: Perl ${{ matrix.perl-version }}
    steps:
      - name: Set up for tests
        shell: bash
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: cpanm --installdeps --notest .
      - name: Build
        run: |
          perl Makefile.PL
          make
      - name: Test
        run: make test
      - name: Post results to Slack
        if: ${{ always() && github.repository_owner == 'bestpractical' }}
        uses: welliba/simple-slack-notify@e1ff920c08c147568f1a40cffd47ce1fa7d4d22c
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS }}
        with:
          channel: '#github'
          status: ${{ job.status }}
          success_text: '${env.BRANCH_NAME} Perl ${{ matrix.perl-version }} (${env.GITHUB_RUN_NUMBER}) tests completed successfully'
          failure_text: '${env.BRANCH_NAME} Perl ${{ matrix.perl-version }} (${env.GITHUB_RUN_NUMBER}) tests failed'
          cancelled_text: '${env.BRANCH_NAME} Perl ${{ matrix.perl-version }} (${env.GITHUB_RUN_NUMBER}) tests cancelled'
          fields: |
            [{ "title": "Repository", "value": "Time-ParseDate", "short": true },
            { "title": "URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}?check_suite_focus=true", "short": true }]
